## Transformacion a datos categoricos



In [2]:
import pandas as pd
import numpy as np
import seaborn as sns

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [4]:
df = pd.read_csv('/content/drive/MyDrive/DATOS/COVID19MEXICO.csv')

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (38) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [4]:
df.columns

Index(['FECHA_ACTUALIZACION', 'ID_REGISTRO', 'ORIGEN', 'SECTOR', 'ENTIDAD_UM',
       'SEXO', 'ENTIDAD_NAC', 'ENTIDAD_RES', 'MUNICIPIO_RES', 'TIPO_PACIENTE',
       'FECHA_INGRESO', 'FECHA_SINTOMAS', 'FECHA_DEF', 'INTUBADO', 'NEUMONIA',
       'EDAD', 'NACIONALIDAD', 'EMBARAZO', 'HABLA_LENGUA_INDIG', 'INDIGENA',
       'DIABETES', 'EPOC', 'ASMA', 'INMUSUPR', 'HIPERTENSION', 'OTRA_COM',
       'CARDIOVASCULAR', 'OBESIDAD', 'RENAL_CRONICA', 'TABAQUISMO',
       'OTRO_CASO', 'TOMA_MUESTRA_LAB', 'RESULTADO_LAB',
       'TOMA_MUESTRA_ANTIGENO', 'RESULTADO_ANTIGENO', 'CLASIFICACION_FINAL',
       'MIGRANTE', 'PAIS_NACIONALIDAD', 'PAIS_ORIGEN', 'UCI'],
      dtype='object')

In [5]:
df.shape

(11808599, 40)

In [6]:
df.head(2)

FECHA_ACTUALIZACION ID_REGISTRO  ORIGEN  ...  PAIS_NACIONALIDAD  PAIS_ORIGEN  UCI
0          2021-11-26      z4e838       1  ...             México           97    2
1          2021-11-26      z2b144       2  ...             México           97   97

[2 rows x 40 columns]

In [7]:
df.dtypes

FECHA_ACTUALIZACION      object
ID_REGISTRO              object
ORIGEN                    int64
SECTOR                    int64
ENTIDAD_UM                int64
SEXO                      int64
ENTIDAD_NAC               int64
ENTIDAD_RES               int64
MUNICIPIO_RES             int64
TIPO_PACIENTE             int64
FECHA_INGRESO            object
FECHA_SINTOMAS           object
FECHA_DEF                object
INTUBADO                  int64
NEUMONIA                  int64
EDAD                      int64
NACIONALIDAD              int64
EMBARAZO                  int64
HABLA_LENGUA_INDIG        int64
INDIGENA                  int64
DIABETES                  int64
EPOC                      int64
ASMA                      int64
INMUSUPR                  int64
HIPERTENSION              int64
OTRA_COM                  int64
CARDIOVASCULAR            int64
OBESIDAD                  int64
RENAL_CRONICA             int64
TABAQUISMO                int64
OTRO_CASO                 int64
TOMA_MUE

In [8]:
df.FECHA_ACTUALIZACION.unique()

array(['2021-11-26'], dtype=object)

In [9]:
df.ORIGEN.unique()

array([1, 2])

In [10]:
df['ORIGEN'] = df['ORIGEN'].replace({1: 'USMER',
                                     2: 'FUERA DE USMER'})

In [11]:
df.SECTOR.unique()

array([12, 13,  6,  3,  8,  9,  4,  5,  2, 11, 10,  7,  1, 99, 14])

In [12]:
df['SECTOR'] = df['SECTOR'].replace({1: 'CRUZ ROJA',
                                     2: 'DIF',
                                     3: 'ESTATAL',
                                     4: 'IMSS',
                                     5: 'IMSS-BIENESTAR',
                                     6: 'ISSTE',
                                     7: 'MUNICIPAL',
                                     8: 'PEMNEX',
                                     9: 'PRIVADA',
                                     10: 'SEDENA',
                                     11: 'SEMAR',
                                     12: 'SSA',
                                     13: 'UNIVERSITARIO',
                                     99: 'NO ESPECIFICADO'})

In [14]:
df.ENTIDAD_UM.unique()

array([ 9, 16, 18,  7, 19, 13, 29, 27, 31, 12, 22,  2, 26, 32,  1,  4,  8,
       23, 24, 15, 14,  5, 17, 10,  3, 21, 30, 20, 28,  6, 11, 25])

In [17]:
df['ENTIDAD_UM'] = df['ENTIDAD_UM'].replace({1: 'AGUASCALIENTES',
                                             2: 'BAJA CALIFORNIA',
                                             3: 'BAJA CALIFORNIA SUR',
                                             4: 'CAMPECHE',
                                             5: 'COAHUILA DE ZARAGOZA',
                                             6: 'COLIMA',
                                             7: 'CHIAPAS',
                                             8: 'CHIHUAHUA',
                                             9: 'CIUDAD DE MÉXICO',
                                             10: 'DURANGO',
                                             11: 'GUANAJUATO',
                                             12: 'GUERRERO',
                                             13: 'HIDALGO',
                                             14: 'JALISCO',
                                             15: 'MÉXICO',
                                             16: 'MICHOACÁN DE OCAMPO',
                                             17: 'MORELOS',
                                             18: 'NAYARIT',
                                             19: 'NUEVO LEÓN',
                                             20: 'OAXACA',
                                             21: 'PUEBLA',
                                             22: 'QUERÉTARO',
                                             23: 'QUINTANA ROO',
                                             24: 'SAN LUIS POTOSÍ',
                                             25: 'SINALOA',
                                             26: 'SONORA',
                                             27: 'TABASCO',
                                             28: 'TAMAULIPAS',
                                             29: 'TLAXCALA',
                                             30: 'VERACRUZ DE IGNACIO DE LA LLAVE',
                                             31: 'YUCATÁN',
                                             32: 'ZACATECAS',
                                             36: 'ESTADOS UNIDOS MEXICANOS',
                                             97: 'NO APLICA',
                                             98:'SE IGNORA',
                                             99: 'NO ESPECIFICADO'})

In [19]:
df.SEXO.unique()

array([2, 1])

In [5]:
df['SEXO'] = df['SEXO'].replace({1: 'MUJER',
                                 2: 'HOMBRE',
                                 3: 'NO ESPECIFICADO'})

In [6]:
df.ENTIDAD_NAC.unique()

array([15, 16, 18,  7,  9, 19, 28, 29, 27, 31, 12,  2, 26, 32, 14, 21,  4,
        8,  1, 24, 23, 10,  5, 17,  3, 30, 25, 22,  6, 11, 13, 20, 99])

In [9]:
df['ENTIDAD_RES'] = df['ENTIDAD_RES'].replace({1: 'AGUASCALIENTES',
                                               2: 'BAJA CALIFORNIA',
                                               3: 'BAJA CALIFORNIA SUR',
                                               4: 'CAMPECHE',
                                               5: 'COAHUILA DE ZARAGOZA',
                                               6: 'COLIMA',
                                               7: 'CHIAPAS',
                                               8: 'CHIHUAHUA',
                                               9: 'CIUDAD DE MÉXICO',
                                               10: 'DURANGO',
                                               11: 'GUANAJUATO',
                                               12: 'GUERRERO',
                                               13: 'HIDALGO',
                                               14: 'JALISCO',
                                               15: 'MÉXICO',
                                               16: 'MICHOACÁN DE OCAMPO',
                                               17: 'MORELOS',
                                               18: 'NAYARIT',
                                               19: 'NUEVO LEÓN',
                                               20: 'OAXACA',
                                               21: 'PUEBLA',
                                               22: 'QUERÉTARO',
                                               23: 'QUINTANA ROO',
                                               24: 'SAN LUIS POTOSÍ',
                                               25: 'SINALOA',
                                               26: 'SONORA',
                                               27: 'TABASCO',
                                               28: 'TAMAULIPAS',
                                               29: 'TLAXCALA',
                                               30: 'VERACRUZ DE IGNACIO DE LA LLAVE',
                                               31: 'YUCATÁN',
                                               32: 'ZACATECAS',
                                               36: 'ESTADOS UNIDOS MEXICANOS',
                                               97: 'NO APLICA',
                                               98:'SE IGNORA',
                                               99: 'NO ESPECIFICADO'})

In [ ]:
df.ENTIDAD_NAC.unique()

In [ ]:
df['ENTIDAD_NAC'] = df['ENTIDAD_NAC'].replace({1: 'AGUASCALIENTES',
                                               2: 'BAJA CALIFORNIA',
                                               3: 'BAJA CALIFORNIA SUR',
                                               4: 'CAMPECHE',
                                               5: 'COAHUILA DE ZARAGOZA',
                                               6: 'COLIMA',
                                               7: 'CHIAPAS',
                                               8: 'CHIHUAHUA',
                                               9: 'CIUDAD DE MÉXICO',
                                               10: 'DURANGO',
                                               11: 'GUANAJUATO',
                                               12: 'GUERRERO',
                                               13: 'HIDALGO',
                                               14: 'JALISCO',
                                               15: 'MÉXICO',
                                               16: 'MICHOACÁN DE OCAMPO',
                                               17: 'MORELOS',
                                               18: 'NAYARIT',
                                               19: 'NUEVO LEÓN',
                                               20: 'OAXACA',
                                               21: 'PUEBLA',
                                               22: 'QUERÉTARO',
                                               23: 'QUINTANA ROO',
                                               24: 'SAN LUIS POTOSÍ',
                                               25: 'SINALOA',
                                               26: 'SONORA',
                                               27: 'TABASCO',
                                               28: 'TAMAULIPAS',
                                               29: 'TLAXCALA',
                                               30: 'VERACRUZ DE IGNACIO DE LA LLAVE',
                                               31: 'YUCATÁN',
                                               32: 'ZACATECAS',
                                               36: 'ESTADOS UNIDOS MEXICANOS',
                                               97: 'NO APLICA',
                                               98:'SE IGNORA',
                                               99: 'NO ESPECIFICADO'})

In [8]:
df.head()

FECHA_ACTUALIZACION ID_REGISTRO  ORIGEN  ...  PAIS_NACIONALIDAD  PAIS_ORIGEN UCI
0          2021-11-26      z4e838       1  ...             México           97   2
1          2021-11-26      z2b144       2  ...             México           97  97
2          2021-11-26      zz7202       1  ...             México           97  97
3          2021-11-26      z58ed3       2  ...             México           97  97
4          2021-11-26      z3be8c       2  ...             México           97  97

[5 rows x 40 columns]